"""cambio de tamano imagenes

Revision ID: 2a0081f62ad4
Revises: 720ac0bcd8d6
Create Date: 2025-10-05 13:48:58.099244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0081f62ad4'
down_revision: Union[str, Sequence[str], None] = '720ac0bcd8d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
