"""cambio de relaciones2

Revision ID: 720ac0bcd8d6
Revises: 7fad38034527
Create Date: 2025-10-04 22:51:43.691779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '720ac0bcd8d6'
down_revision: Union[str, Sequence[str], None] = '7fad38034527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recetamenusemanal_id'), table_name='recetamenusemanal')
    op.drop_column('recetamenusemanal', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recetamenusemanal', sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_recetamenusemanal_id'), 'recetamenusemanal', ['id'], unique=False)
    # ### end Alembic commands ###
