"""cambio de relaciones

Revision ID: 7fad38034527
Revises: ba1843f8713e
Create Date: 2025-10-04 22:18:27.850481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fad38034527'
down_revision: Union[str, Sequence[str], None] = 'ba1843f8713e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recetamenusemanal', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_recetamenusemanal_id'), 'recetamenusemanal', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recetamenusemanal_id'), table_name='recetamenusemanal')
    op.drop_column('recetamenusemanal', 'id')
    # ### end Alembic commands ###
