"""creacion inicial de DB

Revision ID: b8a434d09f44
Revises: 
Create Date: 2025-10-04 17:55:41.254170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a434d09f44'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('menusemanal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.String(length=10), nullable=False),
    sa.Column('fecha_fin', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menusemanal_id'), 'menusemanal', ['id'], unique=False)
    op.create_table('receta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('promt_usuario', sa.Text(), nullable=True),
    sa.Column('instrucciones', sa.Text(), nullable=False),
    sa.Column('imagen_receta_base64', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receta_id'), 'receta', ['id'], unique=False)
    op.create_table('ingredientefaltantereceta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente', sa.String(length=200), nullable=False),
    sa.Column('cantidad', sa.String(length=100), nullable=True),
    sa.Column('unidad_medida', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['receta_id'], ['receta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredientefaltantereceta_id'), 'ingredientefaltantereceta', ['id'], unique=False)
    op.create_table('recetamenusemanal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_semanal_id', sa.Integer(), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_semanal_id'], ['menusemanal.id'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['receta.id'], ),
    sa.PrimaryKeyConstraint('id', 'menu_semanal_id', 'receta_id')
    )
    op.create_index(op.f('ix_recetamenusemanal_id'), 'recetamenusemanal', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recetamenusemanal_id'), table_name='recetamenusemanal')
    op.drop_table('recetamenusemanal')
    op.drop_index(op.f('ix_ingredientefaltantereceta_id'), table_name='ingredientefaltantereceta')
    op.drop_table('ingredientefaltantereceta')
    op.drop_index(op.f('ix_receta_id'), table_name='receta')
    op.drop_table('receta')
    op.drop_index(op.f('ix_menusemanal_id'), table_name='menusemanal')
    op.drop_table('menusemanal')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
