"""cambio de tamano imageneslogntext

Revision ID: ca2f1f6f7c2a
Revises: 2a0081f62ad4
Create Date: 2025-10-05 13:50:10.343362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca2f1f6f7c2a'
down_revision: Union[str, Sequence[str], None] = '2a0081f62ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
